export const blogPosts = [
    {
      id: 1,
      image: "https://static.30shine.com/shop-admin/2023/08/21/30SDAL0J-sap-vuot-toc-side-part-ru.jpg",
      title: " TOP 6+ Sáp vuốt tóc Side Part rủ tạo kiểu tóc Side Part đúng chuẩn",
      shortDesc: "6 loại sáp vuốt tóc Side Part rủ dưới đây sẽ giúp bạn dễ dàng sở hữu kiểu tóc Side Part chuẩn đẹp như minh tinh Hàn Quốc. Cùng tìm hiểu ngay trong bài viết dưới đây. ",
      date: "01/03/2024",
      category: "Đẹp mỗi ngày",
    },
    {
      id: 2,
      image: "https://static.30shine.com/shop-admin/2023/08/21/30S48YAX-sap-vuot-toc-loai-nao-tot.jpg",
      title: "Sáp vuốt tóc loại nào tốt? 10+ Gợi ý anh em không nên bỏ lỡ",
      shortDesc: "Hàng trăm dòng sáp vuốt tóc đến từ nhiều thương hiệu khác nhau trên thị trường khiến anh em bối rối khi lựa chọn, không biết sáp vuốt tóc loại nào tốt? Đừng lo lắng, trong bài viết dưới đây, 30Shine Shop sẽ giới thiệu đến anh em 10+ dòng sáp vuốt tóc chất lượng đến từ các thương hiệu nổi tiếng như Reuzel, Volcanic, Glanzen, Kevin Murphy…. Cùng tham khảo ngay để biết nên mua sáp vuốt tóc loại nào nhé!",
      date: "26/02/2024",
      category: "Tóc đẹp mỗi ngày",
    },
    {
        id: 3,
        image: "https://static.30shine.com/shop-admin/2023/08/16/30SSLINR-cac-loai-pomade.jpg",
        title: "Sáp vuốt tóc loại nào tốt? 10+ Gợi ý anh em không nên bỏ lỡ",
        shortDesc: "Trên thị trường hiện nay đang đầy ắp các loại pomade khác nhau, từ gốc dầu truyền thống cho đến các phiên bản cải tiến như gốc nước, clay pomade, gel pomade… khiến anh em bối rối để lựa chọn 1 sản phẩm ưng ý. Đừng lo lắng, trong bài viết này 30Shine Shop sẽ giúp anh em tìm ra được sản phẩm phù hợp với mình nhất qua 12 gợi ý về loại pomade nên sử dụng trong 2023 cho anh em tham khảo.",
        date: "21/03/2023",
        category: "Da đẹp mỗi ngày",
      }, {
        id: 4,
        image: "https://static.30shine.com/shop-admin/2023/08/16/30STFSO0-sap-vuot-toc-nam-mem.jpg",
        title: "5 loại sáp vuốt tóc nam mềm tự nhiên, giữ nếp cả ngày dài",
        shortDesc: "Lựa chọn được loại sáp vuốt phù hợp với chất tóc sẽ giúp mái tóc giữ được nếp, độ phồng suốt cả ngày dài. Đặc biệt, nếu bạn có chất tóc mỏng thì cần chú ý lựa chọn các sản phẩm phù hợp để có được mái tóc như ý. Nếu bạn chưa tìm được sản phẩm sáp vuốt tóc nam cho tóc mềm phù hợp thì hãy cùng tham khảo 5 loại sáp vuốt tóc nam mềm dưới đây từ 30Shine Shop để chọn ra được “chân ái” cho mình nhé!",
        date: "26/02/2025",
        category: "Tóc đẹp mỗi ngày",
      }, {
        id: 5,
        image: "https://static.30shine.com/shop-admin/2023/08/16/30SB2HK6-sap-vuot-toc-nam-cho-toc-mong.jpg",
        title: "8+ Loại sáp vuốt tóc nam cho tóc mỏng tạo độ bông dày hiệu quả",
        shortDesc: "Sáp vuốt tóc chính là cứu tinh dành cho những chàng trai sở hữu mái tóc mỏng, giúp tạo volume và tăng độ phồng hiệu quả. Tuy nhiên, làm sao để chọn đúng loại sáp vuốt tóc nam cho tóc mỏng mà không gây nặng đầu hay bết dính. Cùng tham khảo ngay những gợi ý sau đây nhé.",
        date: "16/02/2023",
        category: "Tóc đẹp mỗi ngày",
      }, {
        id: 6,
        image: "https://static.30shine.com/shop-admin/2023/08/15/30SEA8ZB-sua-rua-mat-ngan-ngua-mun-cho-nam.jpg",
        title: "Tổng hợp 5+ sữa rửa mặt ngăn ngừa mụn cho nam hiệu quả",
        shortDesc: "Với các đấng mày râu, tình trạng mụn xuất hiện có thể bắt nguồn từ việc làm sạch da không đúng cách. Do đó, việc chọn sữa rửa mặt ngăn ngừa cho nam sao cho phù hợp là điều cần thiết. Dưới đây là TOP 5+ sữa rửa mặt làm giảm mụn cho nam đáng dùng mà các anh em có thể tham khảo!",
        date: "15/05/2024",
        category: "Da đẹp mỗi ngày",
      }, {
        id: 7,
        image: "https://static.30shine.com/shop-admin/2023/08/15/30S73ARH-sua-rua-mat-cho-nam-da-kho.jpg",
        title: "TOP 7+ loại sữa rửa mặt cho nam da khô | pH thấp, dưỡng ẩm tốt",
        shortDesc: "Nam giới có làn da khô cần chú ý đến việc sử dụng sữa rửa mặt bởi nếu rửa mặt với sản phẩm không phù hợp thì sẽ khiến da càng khô hơn, từ đó dẫn đến các tình trạng kích ứng, viêm da, da xỉn màu,... thậm chí là lão hoá sớm. Hãy cùng 30Shine Shop đi tìm những sữa rửa mặt cho nam da khô được đánh giá cao trong bài viết dưới đây! ",
        date: "20/02/2024",
        category: "Da đẹp mỗi ngày",
      },
      {
        id: 8,
        image: "https://static.30shine.com/shop-admin/2023/08/15/30S0LBOM-sap-vuot-toc-nam-khong-bong.jpg",
        title: "TOP 5+ sáp vuốt tóc nam không bóng tạo texture tự nhiên nhất ",
        shortDesc: "Sáp vuốt tóc nam không bóng là sản phẩm chăm sóc tóc dùng để tạo kiểu tóc bóng mờ trong 2 - 3 tiếng, phù hợp với những người muốn tạo kiểu tóc tự nhiên, không tạo ra vẻ bóng bẩy. Dưới đây là TOP 5+ sáp vuốt tóc không bóng dành cho nam hot nhất hiện nay mà bạn có thể tham khảo!",
        date: "05/07/2025",
        category: "Tóc đẹp mỗi ngày",
      }, {
        id: 9,
        image: "https://static.30shine.com/shop-admin/2023/08/15/30SLXSXU-dau-goi-lam-sach-gau-cho-nam.jpg",
        title: "Top 10+ dầu gội làm sạch gàu cho nam nên sử dụng 2025",
        shortDesc: "Da đầu xuất hiện gàu là một vấn đề phổ biến, không chỉ gây khó chịu mà còn ảnh hưởng trực tiếp đến ngoại hình và sự tự tin của nam giới. Để giúp anh em vượt qua vấn đề này, 30Shine Shop đã tổng hợp danh sách top 10 dầu gội làm sạch gàu cho nam hiệu quả, giúp bạn lấy lại sự tự tin và ngoại hình của mình. ",
        date: "06/06/2025",
        category: "Tóc đẹp mỗi ngày",
      }, {
        id: 10,
        image: "https://static.30shine.com/shop-admin/2023/08/07/30S8NR6W-cham-soc-da-mat-nam.jpg",
        title: "Chăm sóc da mặt cho nam: 8+ sai lầm phổ biến khiến “tiền mất tật mang”",
        shortDesc: "Làm thế nào để chăm sóc da mặt cho nam đúng cách là vấn đề được nhiều “phái mạnh” vô cùng quan tâm, đặc biệt là với những anh em có làn da nhạy cảm và đang gặp vấn đề về mụn. Bài viết dưới đây sẽ hé lộ “8 sai lầm phổ biến trong cách chăm sóc da mặt nam” mà gần 90% anh em đang mắc phải. Kéo xuống và tìm hiểu ngay!",
        date: "20/03/2025",
        category: "Tóc đẹp mỗi ngày",
      },
  ];
  